import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import {
	getAutogeneratedPostOG,
	getAutogeneratedPublicationOG,
} from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps, GetStaticPropsContext } from 'next';
import Head from 'next/head';
import { useRef } from 'react';
import { twJoin } from 'tailwind-merge';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { PostHeader } from '../components/post-header';
import PostPageNavbar from '../components/post-page-navbar';
import { useReadingProgress } from '../hooks/useReadingProgress';
import ReadingProgressWithBackToTop from '../components/reading-progress-with-back-to-top';
import PublicationFooter from '../components/publication-footer';
import { LazySeriesWrapper } from '../components/lazy-series-wrapper';
import StaticPageContent from '../components/static-page-content';
import { useRouter } from 'next/router';
import { useEnvironmentTitle } from '../hooks/useEnvironmentTitle';
import { NextIntlClientProvider } from 'next-intl';
import GSPExtensionPopup from '../components/gsp-extension-popup';
import {
	MorePostsByPublicationDocument,
	MorePostsEdgeFragment,
	PageByPublicationDocument,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';
import { getTimezoneFromLocale } from '../utils/timezone';
import { replaceLegacyPublicationUrl } from '../utils/urls';

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
	morePosts: MorePostsEdgeFragment[];
	messages: any;
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
	messages: any;
};

type Props = PostProps | PageProps;

const Post = ({ publication, post, morePosts }: PostProps) => {
	const router = useRouter();
	const currentLocale = router.locale || 'en';
	const postTitle = useEnvironmentTitle(post.seo?.title || post.title);
	const canonicalPostUrl = replaceLegacyPublicationUrl(post.url);
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	return (
		<>
			<Head>
				<title>{postTitle}</title>
				<link rel="canonical" href={canonicalPostUrl || ''} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />

				{/* Basic SEO meta tags */}
				<meta name="keywords" content={post.tags?.map(tag => tag.name).join(', ') || ''} />
				<meta name="author" content={post.author.name} />
				<meta name="robots" content="index, follow" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="language" content={currentLocale} />

				<meta property="og:type" content="article" />
				<meta property="og:title" content={post.seo?.title || post.title} />
				<meta property="og:description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="og:url" content={canonicalPostUrl || ''} />
				<meta property="og:site_name" content={publication.title} />
				<meta property="og:locale" content={currentLocale.replace('-', '_')} />
				{post.publishedAt && <meta property="article:published_time" content={post.publishedAt} />}
				{post.updatedAt && <meta property="article:modified_time" content={post.updatedAt} />}
				<meta property="article:author" content={post.author.name} />
				{post.tags?.map(tag => (
					<meta key={tag.id} property="article:tag" content={tag.name} />
				))}

				{/* Twitter Card meta tags */}
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>

				{/* Image meta tags */}
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				{post.coverImage?.url && (
					<>
						<meta property="og:image:alt" content={post.title} />
						<meta property="og:image:type" content="image/jpeg" />
						<meta property="og:image:width" content="1200" />
						<meta property="og:image:height" content="630" />
					</>
				)}

				{/* Additional meta tags */}
				<meta name="theme-color" content="#ffffff" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="format-detection" content="telephone=no" />

				{/* Schema.org structured data */}
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<PostHeader post={post} morePosts={morePosts} />
			{post.series?.slug && (
				<LazySeriesWrapper
					seriesSlug={post.series.slug}
					host={process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST}
					currentPostSlug={post.slug}
				/>
			)}
			<GSPExtensionPopup post={post} />
		</>
	);
};

const Page = ({ page, publication }: PageProps) => {
	const router = useRouter();
	const currentLocale = router.locale || 'en';
	const title = useEnvironmentTitle(page.title);
	const description = page.content?.markdown?.substring(0, 160) || title;
	const pageUrl = `${publication.url}/${page.slug}`;
	const ogImage = publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication);
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	return (
		<>
			<Head>
				<title>{title}</title>
				<link rel="canonical" href={pageUrl} />
				<meta name="description" content={description} />
				<meta name="robots" content="index, follow" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="language" content={currentLocale} />

				{/* Open Graph meta tags */}
				<meta property="og:type" content="website" />
				<meta property="og:url" content={pageUrl} />
				<meta property="og:title" content={title} />
				<meta property="og:description" content={description} />
				<meta property="og:image" content={ogImage} />

				{/* Twitter Card meta tags */}
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={title} />
				<meta property="twitter:description" content={description} />
				<meta property="twitter:image" content={ogImage} />

				{/* Additional meta tags */}
				<meta name="theme-color" content="#ffffff" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="format-detection" content="telephone=no" />

				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<StaticPageContent pageContent={page} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const router = useRouter();
	const headerRef = useRef<HTMLElement | null>(null);

	// Reading progress hook
	const readingProgress = useReadingProgress();

	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;
	const navPositionStyles =
		'relative transform-none md:sticky md:top-0 md:left-0 md:backdrop-blur-lg';

	if (props.type === 'post') {
		return (
			<NextIntlClientProvider
				locale={router.locale}
				messages={props.messages}
				timeZone={getTimezoneFromLocale(router.locale ?? 'en')}
			>
				{/* Reading Progress Bar */}
				<ReadingProgressWithBackToTop progress={readingProgress} />

				<AppProvider publication={publication} post={props.post}>
					<Layout>
						<header
							ref={headerRef}
							className={twJoin(
								'blog-header',
								'z-50 w-full border-b',
								navPositionStyles,
								'border-black/10 bg-white bg-opacity-70 dark:border-white/10 dark:bg-slate-900 dark:bg-opacity-70',
							)}
						>
							<PostPageNavbar publication={publication} ref={headerRef} />
						</header>
						<Container className="px-4 md:px-6 lg:px-8">
							<article className="flex flex-col items-start gap-10 pb-10">
								<Post {...props} />
							</article>
						</Container>				<PublicationFooter
						authorName={publication.author.name}
						title={publication.title}
						imprint={publication.imprint}
						disableFooterBranding={publication.preferences.disableFooterBranding}
						isTeam={publication.isTeam}
						logo={publication.preferences.logo}
					/>
					</Layout>
				</AppProvider>
			</NextIntlClientProvider>
		);
	}

	const description =
		publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`;

	return (
		<NextIntlClientProvider
			locale={router.locale}
			messages={props.messages}
			timeZone={getTimezoneFromLocale(router.locale ?? 'en')}
		>
			{/* Reading Progress Bar */}
			<ReadingProgressWithBackToTop progress={readingProgress} />

			<AppProvider publication={publication} post={maybePost} page={maybePage}>
				<Layout>
					<Head>
						<title>
							{publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
						</title>
						<meta name="description" content={description} />
						<meta property="twitter:card" content="summary_large_image" />
						<meta
							property="twitter:title"
							content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
						/>
						<meta property="twitter:description" content={description} />
						<meta
							property="og:image"
							content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
						/>
						<meta
							property="twitter:image"
							content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
						/>
						<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<header
					ref={headerRef}
					className={twJoin(
						'blog-header',
						'z-50 w-full border-b',
						navPositionStyles,
						'border-black/10 bg-white bg-opacity-70 dark:border-white/10 dark:bg-slate-900 dark:bg-opacity-70',
					)}
				>
					<PostPageNavbar publication={publication} ref={headerRef} />
				</header>
				<Container className="px-4 md:px-6 lg:px-8">
					<article className="flex flex-col items-start gap-10 pb-10">
						<Page {...props} />
					</article>
				</Container>
				<PublicationFooter
					authorName={publication.author.name}
					title={publication.title}
					imprint={publication.imprint}
					disableFooterBranding={publication.preferences.disableFooterBranding}
					isTeam={publication.isTeam}
					logo={publication.preferences.logo}
					hideBackToTop={true}
				/>
			</Layout>
		</AppProvider>
	</NextIntlClientProvider>
);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async (context: GetStaticPropsContext) => {
	const { params, locale = 'en' } = context;

	if (!params) {
		throw new Error('No params');
	}

	// Load messages for the current locale
	const messages = (await import(`../messages/${locale}.json`)).default;

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	try {
		const [postData, morePostsData] = await Promise.all([
			request(endpoint, SinglePostByPublicationDocument, { host, slug }),
			request(endpoint, MorePostsByPublicationDocument, { first: 4, host }),
		]);

		if (postData.publication?.post) {
			const normalizedPublication = {
				...postData.publication,
				url: replaceLegacyPublicationUrl(postData.publication.url),
			};

			const normalizedPost = {
				...postData.publication.post,
				url: replaceLegacyPublicationUrl(postData.publication.post.url),
			};

			const normalizedMorePosts = (morePostsData.publication?.posts.edges ?? []).map((edge) => ({
				...edge,
				node: {
					...edge.node,
					url: replaceLegacyPublicationUrl(edge.node.url),
				},
			}));

			return {
				props: {
					type: 'post',
					post: normalizedPost,
					morePosts: normalizedMorePosts,
					publication: normalizedPublication,
					messages,
				},
				revalidate: 1,
			};
		}

		const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

		if (pageData.publication?.staticPage) {
			const normalizedPublication = {
				...pageData.publication,
				url: replaceLegacyPublicationUrl(pageData.publication.url),
			};

			return {
				props: {
					type: 'page',
					page: pageData.publication.staticPage,
					publication: normalizedPublication,
					messages,
				},
				revalidate: 1,
			};
		}

		return {
			notFound: true,
			revalidate: 1,
		};
	} catch (error) {
		console.error('Error fetching data:', error);

		return {
			notFound: true,
			revalidate: 1,
		};
	}
};

export async function getStaticPaths() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => {
			return {
				params: {
					slug: slug,
				},
			};
		}),
		fallback: 'blocking',
	};
}
