import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import {
	getAutogeneratedPostOG,
	getAutogeneratedPublicationOG,
} from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticPaths, GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { useRef } from 'react';
import { twJoin } from 'tailwind-merge';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { PostHeader } from '../components/post-header';
import PostPageNavbar from '../components/post-page-navbar';
import PublicationFooter from '../components/publication-footer';
import { LazySeriesWrapper } from '../components/lazy-series-wrapper';
import StaticPageContent from '../components/static-page-content';
import {
	MorePostsByPublicationDocument,
	MorePostsEdgeFragment,
	PageByPublicationDocument,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
	morePosts: MorePostsEdgeFragment[];
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
};

type Props = PostProps | PageProps;

const Post = ({ publication, post, morePosts }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />

				{/* Basic SEO meta tags */}
				<meta name="keywords" content={post.tags?.map(tag => tag.name).join(', ') || ''} />
				<meta name="author" content={post.author.name} />
				<meta name="robots" content="index, follow" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="language" content="en" />

				<meta property="og:type" content="article" />
				<meta property="og:title" content={post.seo?.title || post.title} />
				<meta property="og:description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="og:url" content={post.url} />
				<meta property="og:site_name" content={publication.title} />
				<meta property="og:locale" content="en_US" />
				{post.publishedAt && <meta property="article:published_time" content={post.publishedAt} />}
				{post.updatedAt && <meta property="article:modified_time" content={post.updatedAt} />}
				<meta property="article:author" content={post.author.name} />
				{post.tags?.map(tag => (
					<meta key={tag.id} property="article:tag" content={tag.name} />
				))}

				{/* Twitter Card meta tags */}
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>

				{/* Image meta tags */}
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				{post.coverImage?.url && (
					<>
						<meta property="og:image:alt" content={post.title} />
						<meta property="og:image:type" content="image/jpeg" />
						<meta property="og:image:width" content="1200" />
						<meta property="og:image:height" content="630" />
					</>
				)}

				{/* Additional meta tags */}
				<meta name="theme-color" content="#ffffff" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="format-detection" content="telephone=no" />

				{/* Schema.org structured data */}
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<PostHeader post={post} morePosts={morePosts} />
			{post.series?.slug && (
				<LazySeriesWrapper
					seriesSlug={post.series.slug}
					host={process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST}
					currentPostSlug={post.slug}
				/>
			)}
		</>
	);
};

const Page = ({ page }: PageProps) => {
	const title = page.title;
	const description = page.content?.markdown?.substring(0, 160) || title;
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content={description} />
				<meta name="robots" content="index, follow" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="language" content="vi" />

				{/* Open Graph meta tags */}
				<meta property="og:type" content="website" />
				<meta property="og:title" content={title} />
				<meta property="og:description" content={description} />

				{/* Twitter Card meta tags */}
				<meta property="twitter:card" content="summary" />
				<meta property="twitter:title" content={title} />
				<meta property="twitter:description" content={description} />

				{/* Additional meta tags */}
				<meta name="theme-color" content="#ffffff" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="format-detection" content="telephone=no" />
				
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<StaticPageContent pageContent={page} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const headerRef = useRef<HTMLElement | null>(null);
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;
	const navPositionStyles =
		'relative transform-none md:sticky md:top-0 md:left-0 md:backdrop-blur-lg';

	if (props.type === 'post') {
		return (
			<AppProvider publication={publication} post={props.post}>
				<Layout>
					<header
						ref={headerRef}
						className={twJoin(
							'blog-header',
							'z-50 w-full border-b',
							navPositionStyles,
							'border-black/10 bg-white bg-opacity-70 dark:border-white/10 dark:bg-slate-900 dark:bg-opacity-70',
						)}
					>
						<PostPageNavbar publication={publication} ref={headerRef} />
					</header>
					<Container className="px-4 md:px-6 lg:px-8">
						<article className="flex flex-col items-start gap-10 pb-10">
							<Post {...props} />
						</article>
					</Container>				<PublicationFooter
					authorName={publication.author.name}
					title={publication.title}
					imprint={publication.imprint}
					disableFooterBranding={publication.preferences.disableFooterBranding}
					isTeam={publication.isTeam}
					logo={publication.preferences.logo}
				/>
				</Layout>
			</AppProvider>
		);
	}

	const description =
		publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`;

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage}>
			<Layout>
				<Head>
					<title>
						{publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
					</title>
					<meta name="description" content={description} />
					<meta property="twitter:card" content="summary_large_image" />
					<meta
						property="twitter:title"
						content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
					/>
					<meta property="twitter:description" content={description} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<header
					ref={headerRef}
					className={twJoin(
						'blog-header',
						'z-50 w-full border-b',
						navPositionStyles,
						'border-black/10 bg-white bg-opacity-70 dark:border-white/10 dark:bg-slate-900 dark:bg-opacity-70',
					)}
				>
					<PostPageNavbar publication={publication} ref={headerRef} />
				</header>
				<Container className="px-4 md:px-6 lg:px-8">
					<article className="flex flex-col items-start gap-10 pb-10">
						<Page {...props} />
					</article>
				</Container>
				<PublicationFooter
					authorName={publication.author.name}
					title={publication.title}
					imprint={publication.imprint}
					disableFooterBranding={publication.preferences.disableFooterBranding}
					isTeam={publication.isTeam}
					logo={publication.preferences.logo}
				/>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};
export const getStaticProps: GetStaticProps<Props, Params> = async ({ params, locale = 'en' }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const [postData, morePostsData] = await Promise.all([
		request(endpoint, SinglePostByPublicationDocument, { host, slug }),
		request(endpoint, MorePostsByPublicationDocument, { first: 4, host }),
	]);
	if (postData.publication?.post) {
		return {
			props: {
				type: 'post',
				post: postData.publication.post,
				morePosts: morePostsData.publication?.posts.edges ?? [],
				publication: postData.publication,
				...(await serverSideTranslations(locale, ['common'])),
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
				...(await serverSideTranslations(locale, ['common'])),
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export const getStaticPaths: GetStaticPaths = async () => {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	// Import i18n config to get all supported locales
	const i18nConfig = require('../next-i18next.config.js');
	const supportedLocales = i18nConfig.i18n.locales;

	return {
		paths: postSlugs.flatMap((slug) => 
			supportedLocales.map((locale) => ({
				params: { slug },
				locale,
			}))
		),
		fallback: 'blocking',
	};
};
